# Generated by Django 3.1.1 on 2020-09-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.TextField(verbose_name='Код')),
                ('mask', models.CharField(max_length=100, verbose_name='Маска')),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Код типа')),
            ],
        ),
    ]
